.Dd October 6, 2015
.Dt LOGIN 8
.Os
.Sh NAME
.Nm login
.Nd authenticate users and run personal session
.Sh SYNOPSIS
.Nm login
.Sh DESCRIPTION
.Nm login
interactively authenticates users by asking them to enter their username and
password.
The passwords are checked against the password hashes in
.Pa /etc/passwd
as described in
.Xr passwd 5 .
.Nm login
creates a session as the requested user upon successful authentication.
.Pp
.Nm login
has a graphical interface if the display is graphical and uses a textual
interface otherwise.
The textual interface is forced if
.Pa /etc/login.conf.textual
exists.
The process remains running in the background and takes over again when the user
session exits.
.Pp
The user's
.Xr session 5
is created upon login by running the user's
.Pa ~/.session
script if it exists and is executable, otherwise attempting
.Pa /etc/session ,
and ultimately falling back on the user's shell from
.Xr passwd 5 .
It can be overriden by suffixing the username with a colon and the name of the
program to launch.
If the program name is skipped, the login shell is launched.
.Pp
Type a special username to perform special options:
.Pp
.Bl -tag -width "poweroff" -compact -offset indent
.It exit
alias for poweroff
.It poweroff
exit asking for powering off the computer
.It reboot
exit asking for rebooting the computer
.It halt
exit asking for halting the computer
.It reinit
exit asking for reinitializing the system
.El
.Sh SECURITY
There is currently no method to confirm the login screen is in fact real other
than witnessing a pristine boot.
Local users can log in and show a counterfeit login screen that look and behave
like the real
.Nm login
program and trick the next user into revealing their password.
.Sh ENVIRONMENT
.Nm login
sets the following environment variables to match the authenticated user:
.Bl -tag -width "LOGNAME"
.It Ev HOME
home directory
.It Ev LOGNAME
username
.It Ev SHELL
shell
.It Ev USER
username
.El
.Sh FILES
.Bl -tag -width "/etc/login.conf.textual" -compact
.It Pa ~/.session
user session script run upon login (see
.Xr session 5 )
.It Pa /etc/login.conf.textual
textual interface is forced if this file exists
.It Pa /etc/passwd
user database (see
.Xr passwd 5 )
.It Pa /etc/session
fallback session script run upon login (see
.Xr session 5 )
.It Pa /var/run/nologin
Further non-privileged logins are prohibited if this file exists and users
attempting to log in are shown the contents of this file (see
.Xr shutdown 8 )
.El
.Sh EXIT STATUS
.Nm login
exits 0 if the computer should power off, exits 1 if the computer should
reboot, exits 2 on fatal failure and the boot should halt, or exits 3 if the
system should reinitialize.
.Sh SEE ALSO
.Xr passwd 1 ,
.Xr crypt_checkpass 3 ,
.Xr passwd 5 ,
.Xr session 5 ,
.Xr init 8 ,
.Xr shutdown 8
.Sh BUGS
.Nm login
only supports a single monitor.
The mouse code is less than perfect.
