.Dd September 29, 2016
.Dt CHKBLAYOUT 1
.Os
.Sh NAME
.Nm chkblayout
.Nd change the current keyboard layout
.Sh SYNOPSIS
.Nm
.Ar layout
.Nm
.Fl l
.Sh DESCRIPTION
.Nm
changes the current keyboard layout.  Changes do not persist across reboots.
The keyboard layout applied on boot can be configured in
.Pa /etc/kblayout
(see
.Xr kblayout 5 ) .
.Pp
The options are as follows:
.Bl -tag -width "12345678"
.It Fl l, Fl \-list
List out the keymaps installed on the system
.El
.Sh FILES
.Bl -tag -width "/share/kblayout" -compact
.It Pa /share/kblayout
Keyboard layouts.
.El
.Sh EXIT STATUS
.Nm
will exit 0 on success and non-zero otherwise.
.Sh SEE ALSO
.Xr kblayout 5