.Dd December 13, 2021
.Dt POWEROFF 8
.Os
.Sh NAME
.Nm poweroff
.Nd power off the computer
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
gracefully powers off the computer by sending a request to the appropriate
.Xr init 8
process.
.Sh EXIT STATUS
.Nm
will exit 0 on success and non-zero otherwise.
.Sh SEE ALSO
.Xr halt 8 ,
.Xr init 8 ,
.Xr reboot 8
